spring:
  kafka:
    # 需要在主机的hosts中配置地址映射
    bootstrap-servers:
      - http://192.168.3.5:9092
      - http://192.168.3.5:9093
      - http://192.168.3.5:9094
    consumer:
      group-id: consumer-group1-test
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 批量消费一次最大拉取的数据量
      max-poll-records: 100
#      bootstrap-servers: 192.168.3.5:9092,192.168.3.5:9093,192.168.3.5:9094
#      auto-offset-reset: latest                           #最早未被消费的offset earliest
#      max-poll-records: 3100                              #批量消费一次最大拉取的数据量
#      enable-auto-commit: false                           #是否开启自动提交
#      auto-commit-interval: 1000                          #自动提交的间隔时间
#      session-timeout: 20000                              #连接超时时间
#      max-poll-interval: 15000                            #手动提交设置与poll的心跳数,如果消息队列中没有消息，等待毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
#      max-partition-fetch-bytes: 15728640                 #设置拉取数据的大小,15M
    listener:
      concurrency: 3
      ack-mode: MANUAL